=== jrTilak/lazykit/src/www/public/schema/config.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "LazyKit Configuration",
  "description": "Configuration schema for the LazyKit CLI settings.",
  "type": "object",
  "properties": {
    "v": {
      "type": "string",
      "description": "Version of the LazyKit CLI.",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "language": {
      "type": "string",
      "description": "Programming language for the project.",
      "enum": [
        "typescript",
        "javascript"
      ]
    },
    "separate": {
      "type": "boolean",
      "description": "Determines if LazyKit config is stored separately or within package.json."
    },
    "paths": {
      "type": "object",
      "description": "Specifies directories for helper functions and React hooks.",
      "properties": {
        "helperFunctions": {
          "type": "string",
          "description": "Path to store helper functions, relative to the project root."
        },
        "reactHooks": {
          "type": "string",
          "description": "Path to store React hooks, relative to the project root."
        }
      },
      "required": [
        "helperFunctions",
        "reactHooks"
      ]
    },
    "filenameConvention": {
      "type": "object",
      "description": "Defines naming conventions for filenames.",
      "properties": {
        "helperFunctions": {
          "type": "string",
          "description": "Naming convention for helper functions.",
          "enum": [
            "camelCase",
            "kebab-case"
          ]
        },
        "reactHooks": {
          "type": "string",
          "description": "Naming convention for React hooks.",
          "enum": [
            "camelCase",
            "kebab-case"
          ]
        }
      },
      "required": [
        "helperFunctions",
        "reactHooks"
      ]
    },
    "resolve": {
      "type": "object",
      "description": "Defines alias paths for specific directories.",
      "properties": {
        "alias": {
          "type": "object",
          "description": "Record of alias names and their corresponding paths.",
          "additionalProperties": {
            "type": "string",
            "description": "Path to the directory, relative to the project root."
          }
        }
      }
    }
  },
  "required": [
    "v",
    "language",
    "separate",
    "paths",
    "filenameConvention"
  ],
  "additionalProperties": false
}

=== jrTilak/lazykit/src/cli/lazykit.config.json
{
  "$schema": "https://lazykit.jrtilak.dev/schema/config.json",
  "language": "typescript",
  "separate": true,
  "v": "2.0.1",
  "filenameConvention": {
    "helperFunctions": "kebab-case",
    "reactHooks": "kebab-case"
  },
  "paths": {
    "helperFunctions": "@/helpers",
    "reactHooks": "@/hooks"
  },
  "resolve": {
    "alias": {
      "@/helpers": "/src/helpers",
      "@/hooks": "/src/hooks"
    }
  }
}
